### ISSUE TITLE
M4.5

### ISSUE THREAD

**Issue by juliangruber** [space-meridian/roadmap#104]
_Previous milestone: [M4.4](https://github.com/filecoin-station/roadmap/issues/90)_

ETA: 2024-06-09

### Tasks
- [x] https://github.com/filecoin-station/roadmap/issues/107
- [x] https://github.com/filecoin-station/roadmap/issues/109
- [ ] https://github.com/filecoin-station/roadmap/issues/105
- [x] https://github.com/filecoin-station/spark-api/issues/293
- [x] https://github.com/filecoin-station/desktop/issues/1548
- [ ] https://github.com/filecoin-station/roadmap/issues/92
- [ ] https://github.com/filecoin-station/roadmap/issues/94
- [ ] https://github.com/filecoin-station/roadmap/issues/71
- [ ] https://github.com/filecoin-station/desktop/issues/1552
- [ ] #117

## Stretch goals
- [ ] Unify blog vertical spacing through CSS rules
- [ ] https://github.com/filecoin-station/roadmap/issues/100
- [ ] https://github.com/filecoin-station/core/issues/472
- [ ] https://github.com/filecoin-station/spark-api/issues/311
- [ ] https://github.com/filecoin-station/spark/issues/38
- [ ] Track weekly stats (participants, station instances)
