### ISSUE TITLE
Meridian Roadmap H2 2024

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#113]
ETA: 2024-12-18

View the roadmap here: https://starmap.site/roadmap/github.com/pace-meridian/roadmap/issues/113

- [x] https://github.com/space-meridian/roadmap/issues/116
- [x] https://github.com/space-meridian/roadmap/issues/121
- [x] https://github.com/space-meridian/roadmap/issues/131
- [x] https://github.com/space-meridian/roadmap/issues/152
- [x] https://github.com/space-meridian/roadmap/issues/167
- [x] https://github.com/space-meridian/roadmap/issues/181
- [x] https://github.com/space-meridian/roadmap/issues/195
