### ISSUE TITLE
API & dashboard showing RSR for HTTP retrievals (HTTP-RSR)

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#192]
At the moment, Spark RSR is defined as _how many retrievals succeeded using HTTP or Graphsync protocol for CAR transfer_.

Let's add another RSR (HTTP-RSR) defined as follows: _how many retrievals succeeded using HTTP protocol for CAR transfer_. (A retrieval that had to use Graphsync because the SP does not advertise HTTP is considered as a failure.)

We should provide all usual flavours for this RSR:
- Network-wide RSR from all measurements 
- Network-wide RSR using only measurements targeting miners with non-zero HTTP-RSR rate
- Per-miner RSR

What are the benefits:
- Spark v2 will support only HTTP, not Graphsync. The new HTTP-RSR score will show us the gap - how bad the breaking change between Spark v1 and v2 will be. (Note that this does not paint the full picture as there will be more breaking changes between Spark v1 and v2.)
- Spark RSR consumers like the FIL+ Allocator Compliance process can start issuing a warning to SPs that don't offer HTTP retrievals. They can even decide to switch from the current RSR to HTTP-RSR in the future.

Why I want to keep the current RSR around:
- Don't break our chart showing how Spark drove improvements in the RSR over time.
- Avoid breaking changes to consumers. Let them decide the right time to switch and how to make the switch least disrupting to their users.

/cc @willscott, you were interested in having this data

**Tasks**

_Note: We already collect "successful" and "total" retrieval checks. RSR is calculated as `successful/total`. HTTP-RSR calculation can use the same "total" field; we need to add a new field called e.g. "successful_http". HTTP-RSR is then calculated as `sucessful_http/total`._

- [x] Add HTTP-RSR to per-round stats written to InfluxDB, see [spark-evaluate/lib/retrieval-stats.js](https://github.com/filecoin-station/spark-evaluate/blob/607d836f6a60b9b22c57254d6df041dcd4c1cf5f/lib/retrieval-stats.js#L103-L110).
- [x] Expose per-round network-wide HTTP-RSR in the [Spark Internal Dashboard](https://spacemeridian.grafana.net/d/c4bd3c80-9360-4ea3-8b75-c5ecea907659/spark-internal-dashboard).
- [x] Add HTTP-RSR to daily retrieval stats. See [updateRetrievalStats()](https://github.com/filecoin-station/spark-evaluate/blob/607d836f6a60b9b22c57254d6df041dcd4c1cf5f/lib/public-stats.js#L42-L57).
- [x] Add HTTP-RSR to spark-stats responses. See [fetchRetrievalSuccessRate()](https://github.com/filecoin-station/spark-stats/blob/main/stats/lib/stats-fetchers.js#L6-L26), [fetchMinersRSRSummary()](https://github.com/filecoin-station/spark-stats/blob/main/stats/lib/stats-fetchers.js#L208-L225) and [fetchDailyMinerRSRSummary()](https://github.com/filecoin-station/spark-stats/blob/main/stats/lib/stats-fetchers.js#L233-L252).
- [x] Add HTTP-RSR visualisations to Spark Public Dashboard - [network-wide](https://dashboard.filspark.com) and [per-miner](https://dashboard.filspark.com/provider/f03156617). Dashboard source code: https://github.com/filecoin-station/spark-dashboard.
