### ISSUE TITLE
M5.1

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#213]
Based on [Space Meridian Roadmap Q1 2025](https://docs.google.com/document/d/1p0RP5K0fywV3efM3rzU69wgpqisFkl87up1FrUzeVpE/) (internal document).

ETA: 2025-01-31

Previous milestone:

- #195

Next milestone:

- #219

## Carried over

- [ ] #159 @patrickwoodhead
- [x] #208 @pyropy 
- [x] https://github.com/filecoin-station/fil-deal-ingester/issues/23 @pyropy 

## Priorities

1. Spark v1.5
2. Checker Rebrand
3. Spark TTFB + another subnet

## Committed

**Rebrand Station to Checker**

- [x] #215 @patrickwoodhead with support from @juliangruber 
- [x] Migrate GitHub repos to `CheckerNetwork` @juliangruber 

**Spark v1.5 (DDO PoC)**

- [x] https://github.com/filecoin-station/fil-deal-ingester/issues/29 @bajtos 
- [x] https://github.com/space-meridian/roadmap/issues/172 @NikolasHaimerl 
- [x] https://github.com/space-meridian/roadmap/issues/218 @NikolasHaimerl and @bajtos 
- [x] https://github.com/filecoin-station/deal-observer/issues/26 @pyropy 

**Two Checker subnets deployed (Spark + one more)**

- [x] #208 @pyropy (carried over)
- [x] https://github.com/checker-network/arweave/issues/1 @juliangruber @pyropy 

**Keep the systems running**

- [ ] Complete FIL-RetroPGF-2 process (verify test DRIPS transaction, etc.) @patrickwoodhead 

## Stretch Goals

- [ ] #188 @juliangruber

**Other**

- [ ] #207 @pyropy
- [x] #192 @NikolasHaimerl 
- [x] #178
- [ ] https://github.com/filecoin-station/spark-stats-request-metrics/issues/7 @pyropy 

## OUT OF SCOPE

Removed:

**IPNI advertisement correctness checks**

> either by us as a checker subnet, by FIL+ governance or by IPNI itself

The FIDL team will handle this workstream. Do we still want to track it in our GitHub? (Slack discussion: https://space-meridian.slack.com/archives/C076S55SPTN/p1736156922867019)

**Partition Spark data by allocator**

- [x] #193
- [x] #216

**Two Checker subnets deployed (Spark + one more)**

- Platformisation architecture and PoC (this is a placeholder to replace with detailed tasks) @juliangruber 

**Keep the systems running**

- #212
- #168
- https://github.com/filecoin-station/desktop/issues/1997
