### ISSUE TITLE
Public Spark Dashboard MVP

### ISSUE THREAD

**Issue by patrickwoodhead** [space-meridian/roadmap#57]
The funders of Spark would like to have a public dashboard so that they can see the results of Spark.

Currently, the Spark dashboard is on Grafana behind an auth wall. This means only a few people can see the data. We could make this dashboard public but this would open up our database to public internet requests. We need to find a solution whereby the dashboard is public but the database isn't open to the world.

### Product Requirements
- one data point each day and keep this data with unlimited retention, for each chart
- use Grafana for the UI

### Tasks

- [x] Architecture plan for public dashboard
- [x] Chart that shows retrieval success rate
- [x] Chart that shows RSR with a filter by Storage Provider
- [x] Aggregate stats from round evaluations
- [x] Expose stats via REST API
- [x] Average RSR of non zero RSR SPs
- [x] Deals Checked 1d/7d/30d (formerly: CIDs sampled)
- [x] Retrievals performed 1d/7d/30d

### Stretch goals

- Add more columns to the miner RSR table
  - [ ] number of measurements performed
  - [ ] breakdown of common errors (not advertising to IPNI, retrieval failed with 502, etc.)
- [ ] Add a chart to show historic change in success rate for a chosen provider

### Out of scope
-  https://github.com/filecoin-station/spark/issues/34
-  https://github.com/filecoin-station/roadmap/issues/72
-  https://github.com/filecoin-station/roadmap/issues/64

**Comment by bajtos** [comment]
Related issues - potential future ideas:
- https://github.com/filecoin-station/spark/issues/34

**Comment by bajtos** [comment]
Let's aggregate raw data to produce one data point each day and keep this data with unlimited retention.

**Comment by bajtos** [comment]
Retrieval Bot's dashboard for inspiration:

https://retrievalbot-dashboard.vercel.app

**Comment by bajtos** [comment]
Dashboard PoC: https://bajtos.grafana.net/public-dashboards/9af156c3266d4d8384385623d0d2a76c

**Comment by bajtos** [comment]
Public dashboard URL - redirect is configured via Cloudflare:

https://filspark.com/dashboard
