### ISSUE TITLE
M4.2: Two paying Modules, Spark retrievals linked to SPs, Meridian Platform Beginnings

### ISSUE THREAD

**Issue by patrickwoodhead** [space-meridian/roadmap#61]
This is a placeholder issue for M4.2 tickets which will be completed between. The title and scope of this milestone is yet to be confirmed.

ETA: 2024-03-15
(4-5 weeks of work)

```[tasklist]
### Tasks
- [x] Configure fly-log-shipper to write logs in more readable format
- [ ] https://github.com/filecoin-station/roadmap/issues/69
- [ ] https://github.com/filecoin-station/zinnia/issues/489
- [ ] https://github.com/filecoin-station/roadmap/issues/85
- [ ] https://github.com/filecoin-station/roadmap/issues/87
- [ ] https://github.com/filecoin-station/roadmap/issues/73
- [ ] https://github.com/filecoin-station/roadmap/issues/74
- [ ] https://github.com/filecoin-station/roadmap/issues/75
- [ ] https://github.com/filecoin-station/roadmap/issues/64
- [ ] https://github.com/filecoin-station/roadmap/issues/65
- [ ] https://github.com/filecoin-station/spark/issues/40
- [ ] https://github.com/filecoin-station/roadmap/issues/78
- [ ] https://github.com/filecoin-station/roadmap/issues/67
- [ ] https://github.com/filecoin-station/roadmap/issues/82
- [ ] https://github.com/filecoin-station/roadmap/issues/66
- [ ] https://github.com/filecoin-station/roadmap/issues/68
- [ ] https://github.com/filecoin-station/roadmap/issues/83
```

```[tasklist]
### Stretch goals
- [ ] https://github.com/filecoin-station/roadmap/issues/71
- [ ] https://github.com/filecoin-station/roadmap/issues/81
- [ ] https://github.com/filecoin-station/roadmap/issues/80
- [ ] https://github.com/Meridian-IE/impact-evaluator/issues/77
- [ ] https://github.com/filecoin-station/roadmap/issues/57
- [ ] https://github.com/filecoin-station/roadmap/issues/86
- [ ] https://github.com/filecoin-station/roadmap/issues/76
```
