### ISSUE TITLE
Bring down infra cost

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#71]
### Tasks

- [x] Export all InfluxDB data from station bucket
- [x] <del>Upload data export to w3s</del>
- [ ] Hardcode job count offset in queries
  - [x] https://github.com/filecoin-station/site-backend/pull/14
  - [ ] Update Grafana queries
- [x] Turn on retention for all InfluxDB buckets, to bring down Storage cost

**Comment by juliangruber** [comment]
Asked on Slack whether the dashboard work will provide us with total amount of jobs performed. I believe this is the only metric that requires us to have infinite retention on the `station` bucket, which is the main cost factor

**Comment by juliangruber** [comment]
The dashboard work will replace that 👍  So we can turn on a bucket retention policy after these metrics land.

In order to implement some quick cost reductions, I propose we perform a manual purge:
1. Sum the total job count before April 1st 2024
2. Delete all measurements before April 1st 2024
3. Add the previously calculated sum as a fixed offset to Grafana charts and the website

Wdyt @bajtos @patrickwoodhead?

**Comment by juliangruber** [comment]
- [ ] Export measurements before April 1st from Influx
- [ ] Store export
- [ ] Delete measurements before April 1st from Influx
- [ ] Sum total jobs completed
- [ ] Add sum as fixed offset
  - [ ] Grafana
  - [ ] Website

**Comment by bajtos** [comment]
> Export measurements before April 1st from Influx
> Enable 30d bucket retention policy

The 30d retention will delete all data older than April 13th if enabled today. Your export will contain only data older than April 1st. We will lose measurements recorded between April 1st and 13th.

Is that okay? Did I miss something?

**Comment by juliangruber** [comment]
Of course 😅 ok I will include more data in the export.

**Comment by juliangruber** [comment]
Script used for the export, currently running: https://gist.github.com/juliangruber/cd50f1227d08e8b94d6b4b36620b4711

**Comment by juliangruber** [comment]
The export finished. The resulting ndjson file is 58GB in size. Something strange is going on however: It's not including any records with `"_measurement":"jobs-completed"` and `"_field":"value"`. This is what we need to recreate the job count. My suspicion is that the export is incomplete. In comparison, this query works:

<img width="1189" alt="Screenshot 2024-05-14 at 23 36 58" src="https://github.com/filecoin-station/roadmap/assets/10247/5cf80b6b-62ce-4102-b69e-0cd896b7fab2">

I'm going to try to export only these records. I'm also going to repeat the export of everything, to see if it creates a different file.

**Comment by juliangruber** [comment]
This export finished:

```
2024-05-14T23:32:57.724Z { rows: 23382470, jobs: 32774485 }
```

It suggests there were 32m jobs completed, while on the website we show 161m. I will repeat this export to see if it is deterministic.

**Comment by juliangruber** [comment]
Next run:

```
2024-05-16T12:16:11.297Z { rows: 20583385, jobs: 29386919 }
```

This time I used async iteration instead of the `queryRows` function. It looked at significantly less measurements.

**Comment by juliangruber** [comment]
I assume we can improve our chances by performing many queries, maybe one for each day. I will try this now

**Comment by juliangruber** [comment]
The oldest row it can find is from 2022-11-05. We landed the telemetry commit on Oct 31st (https://github.com/filecoin-station/desktop/commit/6d135e6c4e57f7f0e48be5bdf5be6a8eb62f28a1). I don't know what this means.

**Comment by juliangruber** [comment]
Tools for uploading big files to w3s:

- https://web3.storage/docs/go-w3up/
- https://github.com/filecoin-project/data-prep-tools
- https://github.com/anjor/go-fil-dataprep <--
- https://github.com/anjor/carlet

**Comment by juliangruber** [comment]
- downloading measurements from one day takes ~4 minutes
- at the moment the script is at June 28th, 2023
- it will process data until May 1st, 2024
- that's 308 days left
- the script is expected to finish in 21h

**Comment by juliangruber** [comment]
The script ran until `{ day: 2023-10-26T00:00:00.000Z }`, when we started receiving `429 Too Many Requests` / `org XYZ has exceeded limited_query plan limit`.

I'm going to continue the script tomorrow with that date as the new starting point, and will merge the result with the previous export.

**Comment by juliangruber** [comment]
The 1TB disk instance ran out of space. I'm resizing the machine, removing the incomplete day from the export, and then will let it continue

**Comment by juliangruber** [comment]
The script currently is at `2024-01-29` (file size 1.4TB) and has until `2024-06-01` to run.

**Comment by juliangruber** [comment]
Up to `2024-03-03T17:14:30.236298505Z`, there were 567,564,171 jobs recorded in InfluxDB. This is how far my script reached before getting rate limited again. I'm now going to destroy the machine that keeps this export, and enable a retention policy in Influx.

**Comment by juliangruber** [comment]
I will now evaluate deleting these old rows, more work needs to be done before we can turn on a retention policy

**Comment by juliangruber** [comment]
from `2024-03-03T17:14:30.000Z` to `2024-03-03T18:27:50.000Z` there were 1_025_567 more jobs. I suspect we're getting rate limited again.

**Comment by juliangruber** [comment]
I have paused the script as even with a 1s window it was bringing down the Influx cluster

**Comment by juliangruber** [comment]
We are waiting to hear back from the Influx support team, which has taken on this case

**Comment by juliangruber** [comment]
For now, I'm exporting all measurements from web3.storage, to get a job count without needing InfluxDB

**Comment by juliangruber** [comment]
Still exporting Voyager, currently at 3.7TB size

**Comment by juliangruber** [comment]
InfluxDB support told us that up to `2024-07-09T00:00:00Z` to sum of all jobs completed is `155_153_052_475`.

**Comment by juliangruber** [comment]
I've enabled a 90 days retention policy on the "station" bucket. This matches what we have for "peer-checker", "spark-evaluate" and "spark-publish". We can reduce it to 30 days if it's still too expensive.

**Comment by bajtos** [comment]
FWIW, the `daily_stations` table started tracking the number of jobs completed on 2024-06-28. That means we have the data to calculate the total job count after `2024-07-09`. All is good 👍🏻

**Comment by juliangruber** [comment]
Data Graphana + JSON integration doesn't work any more (on PL Grafana), so this has to be reimplemented once the "Station" dashboard has been moved to the Space Meridian Grafana. Hereby, this job is complete finally
